version: '3'

services:

  mysql1:
    image: mysql:8.0.17
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysql}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  app1:
    image: "node:13"
    container_name: app1
    working_dir: /app
    user: "1000:1000"
    volumes:
      - ./webapp:/app
    environment:
      - DBHOST=mysql1
      - NODE_ENV=development
      - PORT=8888
    ports:
      - 80:8888    # External port : container port
    command: npm start

volumes:
  mysql_data:
